### ISSUE TITLE
filename of wildcard certificates  with single quotes with docker

### ISSUE THREAD

**Issue by fiorenzino** [ldez/traefik-certs-dumper#119]
Hi

i have a certificate wildcard in traefik (*.n-ess.it) and the dump produce a file in "not usable name":
./certs/certs
'*.n-ess.it.crt' 
./certs/private/:
'*.n-ess.it.key'
(really, with single quotes)
 
some hacking to correct that?

**Comment by ldez** [comment]
Hello,

I think you have another issue.
could you provide your acme.json (replace the cert and key content by `xxx`)

**Comment by fiorenzino** [comment]
Hi,

i used: 
- ldez/traefik-certs-dumper:latest
- traefik:v1.7.16

in the following:
- docker-compose.yml
- acme.json


docker-compose.yml

```
version: '3'

services:
  traefik-certs-dumper:
    image: ldez/traefik-certs-dumper:latest
    entrypoint: sh -c '
      apk add jq
      ; while ! [ -e /data/acme.json ]
        || ! [ `jq ".Certificates | length" /data/acme.json` != 0 ]; do
          sleep 1
      ; done
      && traefik-certs-dumper file --watch
        --source /data/acme.json --dest /data/certs'
    volumes:
      - ./:/data
  proxy:
    image: traefik:v1.7.16
    command: --configFile=/traefik.toml
    restart: unless-stopped
    # Here's the network we created:
    networks:
      - web
    # The traefik entryPoints
    ports:
      - 80:80
      - 443:443
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:xxxxx.n-ess.it"
      - "traefik.port=8080"
      - "traefik.docker.network=web"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    environment:
            OVH_APPLICATION_KEY: xxxx
            OVH_APPLICATION_SECRET: xxxx
            OVH_CONSUMER_KEY: xxxx
            OVH_ENDPOINT: xxxx

networks:
  web:
    external: true
```

acme.json:

```
{
  "Account": {
    "Email": "xxxx@xxxx",
    "Registration": {
      "body": {
        "status": "valid",
        "contact": [
          "mailto:xxxx@xxxx"
        ]
      },
      "uri": "https://acme-v02.api.letsencrypt.org/acme/acct/98462928"
    },
    "PrivateKey": "xxxxxxx",
    "KeyType": "4096"
  },
  "Certificates": [
    {
      "Domain": {
        "Main": "*.n-ess.it",
        "SANs": [
          "n-ess.it"
        ]
      },
      "Certificate": "xxxxxx",
      "Key": "xxxxxx"
    }
  ],
  "HTTPChallenges": {},
  "TLSChallenges": {}
}
```
