### ISSUE TITLE
Example fails, when you have more than one certresolver configured 

### ISSUE THREAD

**Issue by tobiashochguertel** [ldez/traefik-certs-dumper#134]
I figured out that the [following line makes trouble ](https://github.com/ldez/traefik-certs-dumper/blob/26e5525cefca5721dd5f653744119a9fd1e461ed/docs/docker-compose-traefik-v2.yml#L32)when you have more than one certresolvers activated in your traefik setup:

here a quick way to understand:

![image](https://user-images.githubusercontent.com/3332669/102743920-cbc80b00-4358-11eb-906a-909a674e3797.png)

I modified the test to the following `jq` command:

![image](https://user-images.githubusercontent.com/3332669/102744040-1b0e3b80-4359-11eb-9675-869b87f7fabd.png)

My complete solution:
```
  traefik-certs-dumper:
    image: ldez/traefik-certs-dumper:v2.7.4
    entrypoint: sh -c 'set -x; apk add jq; while ! [ -e /data/acme.json ] || ! [ `jq ".http | .Certificates | length" /data/acme.json` != 0 ]; do sleep 1; done && traefik-certs-dumper file --version v2 --watch --source /data/acme.json --dest ./data/certs'
    volumes:
      - /opt/docker-volumes/traefik:/data
```

Otherwise, `jq ".[] | .Certificates | length"` returns `"22 1"`, and then `... ! [ `jq ".[] | .Certificates | length" /data/acme.json` != 0 ] ...` is evaluated to: `... ! [ 22 1 != 0 ] ...` an you get an Error `sh: 1: unknown operand` or as I was playing around to find this issue: `./bla.sh: line 3: [: too many arguments`

hope this helps, someone who has same issues.

Thanks for this project 👍
