### ISSUE TITLE
Dockerfile and docker-compose

### ISSUE THREAD

**Issue by abate** [ldez/traefik-certs-dumper#2]
Thank you for this ! Exactly what I was looking for !

If you want to use traefik-certs-dumper for other services, you might want to add 
this Dockerfile and docker-compose snippet to the repository.

Once the certs are extracted, you can mount the volume `certs` from another container,
such as `tvial/docker-mailserver` for postifix .

```
FROM alpine:latest

RUN apk add --no-cache git make musl-dev go

RUN git clone https://github.com/ldez/traefik-certs-dumper.git
WORKDIR traefik-certs-dumper
RUN make build
```

```
  certdump:
    build: .
    command: ./traefik-certs-dumper dump --source /acme.json --dest /dump/certs
    volumes:
      - ./acme.json:/acme.json:ro
      - certs:/dump
    restart: "no"
```

**Comment by ldez** [comment]
Thanks :smile_cat: !

I added a Dockerfile inside the project and the images are available here: https://hub.docker.com/r/ldez/traefik-certs-dumper

**Comment by abate** [comment]
this is great ! This is a small script to create certificates to be used with `tvial/docker-mailserver` I just tested.

I love when a plan comes together

```
#!/bin/sh

/usr/bin/traefik-certs-dumper dump \
        --domain-subdir=true \
        --source /acme.json \
        --dest /dump/live

for f in in $(find /dump -name certificate.crt); do
        cd $(dirname $f)
        ln -s certificate.crt fullchain.pem
        ln -s privatekey.key privkey.pem
        cd -
done
```
and the associated `docker-compose.yml`

```
volumes:
  - certs:

services:
  certdump:
    build: .
    volumes:
      - ./acme.json:/acme.json:ro
      - certs:/dump
    restart: "no"
```
