### ISSUE TITLE
[v2.9.2] traefik-certs-dumper not found

### ISSUE THREAD

**Issue by dwydler** [ldez/traefik-certs-dumper#209]
Today I updated the container from 2.9.1 to 2.9.2. After that I got the following error message in the container's log file:
```
traefik-certs-dumper  | + apk add jq
traefik-certs-dumper  | fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/aarch64/APKINDEX.tar.gz
traefik-certs-dumper  | fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/aarch64/APKINDEX.tar.gz
traefik-certs-dumper  | OK: 25 MiB in 30 packages
traefik-certs-dumper  | + '[' -e /data/acme_letsencrypt.json ]
traefik-certs-dumper  | + jq '.dns | .Certificates | length' /data/acme_letsencrypt.json
traefik-certs-dumper  | + '[' 11 '!=' 0 ]
traefik-certs-dumper  | + traefik-certs-dumper file --version v2 --watch --source /data/acme_letsencrypt.json --dest /data/dump
traefik-certs-dumper  | sh: traefik-certs-dumper: not found
traefik-certs-dumper exited with code 127
```
After a downgrade to v2.9.1 the command works again:
```
 ✔ Container traefik-certs-dumper  Started                                                                                                                                              0.2s
traefik-certs-dumper  | + apk add jq
traefik-certs-dumper  | fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/aarch64/APKINDEX.tar.gz
traefik-certs-dumper  | fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/aarch64/APKINDEX.tar.gz
traefik-certs-dumper  | (1/2) Installing oniguruma (6.9.7.1-r0)
traefik-certs-dumper  | (2/2) Installing jq (1.6-r1)
traefik-certs-dumper  | Executing busybox-1.34.1-r7.trigger
traefik-certs-dumper  | OK: 6 MiB in 16 packages
traefik-certs-dumper  | + '[' -e /data/acme_letsencrypt.json ]
traefik-certs-dumper  | + jq '.dns | .Certificates | length' /data/acme_letsencrypt.json
traefik-certs-dumper  | + '[' 11 '!=' 0 ]
traefik-certs-dumper  | + traefik-certs-dumper file --version v2 --watch --source /data/acme_letsencrypt.json --dest /data/dump
traefik-certs-dumper  | + apk add jq
traefik-certs-dumper  | OK: 6 MiB in 16 packages
traefik-certs-dumper  | + '[' -e /data/acme_letsencrypt.json ]
traefik-certs-dumper  | + jq '.dns | .Certificates | length' /data/acme_letsencrypt.json
traefik-certs-dumper  | + '[' 11 '!=' 0 ]
traefik-certs-dumper  | + traefik-certs-dumper file --version v2 --watch --source /data/acme_letsencrypt.json --dest /data/dump
```
My docker-compose.yml looks like this:
```
services:
  traefik-certs-dumper:
    image: ldez/traefik-certs-dumper:latest
    container_name: traefik-certs-dumper
      #    depends_on:
      #      - traefik
    entrypoint: sh -c 'set -x; apk add jq; while ! [ -e /data/acme_letsencrypt.json ] || ! [ `jq ".dns | .Certificates | length" /data/acme_letsencrypt.json` != 0 ]; do sleep 1; done && traefik-certs-dumper file --version v2 --watch --source /data/acme_letsencrypt.json --dest /data/dump'
    labels:
      traefik.enable: false
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

      - "/opt/containers/traefik/data/certificates:/data"
      - ./hook.sh:/hook.sh
    networks:
      proxy-be-traefik-certs-dumper:


networks:
  proxy-be-traefik-certs-dumper:
    external: true
```
So I suspect that the error is related to the change last night?!
